### ISSUE TITLE
"Method RemoveAttribute does not have an implementation"

### ISSUE THREAD

**Issue by CallumWatkins** [warappa/XamlCSS#38]
After trying to follow the getting started guide for more than an hour I still cannot get even the simplest possible WPF app to work with XamlCSS.

I have created a brand new WPF app, installed XamlCSS.WPF 2.0.1 and all its dependencies and placed a button on the main window. Then, no matter how I try to set the stylesheet of the window the app will not start due to an exception.

Methods I have tried:
- Calling `Css.SetStyleSheet(this, CssParser.Parse("Button { ... }"));` in C# from the main window constructor.
- Adding `css:Css.StyleSheet="{DynamicResource styleSheet}"` to the window element in XAML (where `styleSheet` is set in Window.Resources).

 I can see the exception and stack trace in the designer when using the XAML method, and it appears to be a **`NotImplementedException`**.

I am calling `Css.Initialize();` in the main window constructor.

### Exception
> TypeLoadException: Method 'RemoveAttribute' in type 'XamlCSS.WPF.Dom.LogicalDomElement' from assembly 'XamlCSS.WPF, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

### Stack Trace
```
at XamlCSS.WPF.Dom.LogicalTreeNodeProvider.CreateTreeNode(DependencyObject dependencyObject)
at XamlCSS.Dom.TreeNodeProviderBase`3.GetDomElement(TDependencyObject obj)
at XamlCSS.BaseCss`4.UpdateMatchingStyles(TUIElement styleResourceReferenceHolder, StyleSheet styleSheet, TUIElement startFrom)
at XamlCSS.BaseCss`4.CalculateStylesInternal(TUIElement styleResourceReferenceHolder, StyleSheet styleSheet, TUIElement startFrom)
at XamlCSS.BaseCss`4.ExecuteApplyStyles()
at XamlCSS.WPF.Css.<>c.<RenderingHandler>b__1_0(Object sender, EventArgs e)
at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I believe the culprit to be this file [DomElement.cs](https://github.com/warappa/XamlCSS/blob/041ec8a8adc1d945392f82c2ff2dc6f06306a5fa/XamlCSS/Dom/DomElement.cs#L948), yet I cannot understand why this would be a release version of XamlCSS with code that isn't even implemented yet.

If I have missed something really obvious then please let me know, otherwise some help diagnosing this problem would be greatly appreciated.

**Comment by warappa** [comment]
Hi @CallumWatkins,

XamlCSS uses AngleSharp internally. I guess you updated **AngleSharp** to a **_higher version_**. As of your isse, I took a look and indeed, there is at least **1 breaking change** - `RemoveAttibute` returns `bool` instead of `void` in newer versions.

Please try to downgrade AngleSharp to **0.9.8**, this should you get up and running again.

**Comment by CallumWatkins** [comment]
Thank you for the help. I downgraded and although initially still getting errors because of a version redirect in App.config to 0.9.8.1, commenting that out fixed it.

Looks like the dependency criteria need to be modified in the next release of XamlCSS on NuGet to prevent other users making the same mistake.

**Comment by warappa** [comment]
Glad to hear @CallumWatkins!

I'm currently considering this as part of the next update.
